### ISSUE TITLE
Adding a comment to the LinkedPair struct in hashtables.c

### ISSUE THREAD

**Issue by Skidragon** [LambdaSchool/Hash-Tables#36]
When I was working with my pair programming group, we had a hard time parsing LinkedPair as a node for a Linked List. It would be great to have a comment like, "LinkedPair is similar to a node in a linked list, remember from data structures week when creating linked list in Python which are composed of nodes."

This is just a thought that might help for future cohorts, thanks for the great work that you guys are doing!

**Comment by seanchen1991** [comment]
Added a comment as per your suggestion.
